services:
  redis:
    image: redis:7-alpine
    container_name: logistics-db
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
